// Copyright (c) 2020 Kevin L. Mitchell
//
// Licensed under the Apache License, Version 2.0 (the "License"); you
// may not use this file except in compliance with the License.  You
// may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.  See the License for the specific language governing
// permissions and limitations under the License.

// Package lexer is a subpackage of ptk that contains various
// implementations of the ILexer, an interface describing lexers,
// along with related support types and code such as Token.  A lexer
// is an object that can be queried for the next token in a token
// stream; generally, a lexer takes a character stream such as that
// generated by the scanners in the scanner subpackage and groups them
// together into words with semantic meaning.  Its return value is a
// Token, which contains the token type, its location (to be used for
// error reporting), and any meaning associated with the token, such
// as the numerical value of numeric literals.
package lexer
