// Copyright (c) 2020 Kevin L. Mitchell
//
// Licensed under the Apache License, Version 2.0 (the "License"); you
// may not use this file except in compliance with the License.  You
// may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.  See the License for the specific language governing
// permissions and limitations under the License.

// Package parser is a subpackage of ptk that contains the Parser,
// which implements parsing using the Pratt recursive descent
// technique, along with related support types and code such as Node.
// A parser can be queried to extract expressions and statements from
// a lexer; generally, a parser takes a lexer and builds up an
// abstract syntax tree from the tokens generated by the lexer.
package parser
