// Copyright (c) 2020 Kevin L. Mitchell
//
// Licensed under the Apache License, Version 2.0 (the "License"); you
// may not use this file except in compliance with the License.  You
// may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.  See the License for the specific language governing
// permissions and limitations under the License.

// Package visualize contains a Visualize function that may be used to
// generate a printable tree representation of a nested set of Node
// instances.  This may be used to visualize an abstract syntax tree,
// as generated by the parser, but may also be used to visualize other
// tree-like structures, as long as the elements of those structures
// implement the parser.Node interface.  Different profiles exist that
// may be used to alter the visual appearance of the visualized tree.
package visualize
